name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Позволяет запускать workflow вручную

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create ZIP archive
        run: |
          zip -r release.zip . -x README.md update.json .github/*

      - name: Get previous tag
        id: get_previous_tag
        run: |
          echo "Tag: ${{ steps.previoustag.outputs.tag }}"
          echo "Tag N2: ${{ git tag }}"
          if git tag | grep -q .; then
            previous_tag=$(git tag | sort -n | tail -n 1)  # Получаем максимальный тег
            new_tag=$((previous_tag + 1))
          else
            new_tag=1
          fi
          echo "new_tag=${new_tag}" >> $GITHUB_ENV

      - name: Create new release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.new_tag }}  # Используем переменную окружения
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
