name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create ZIP archive
        run: |
          zip -r release.zip . -x README.md update.json .github/*

      - name: Get previous tag
        id: get_previous_tag
        run: |
          previous_tag=$(git describe --tags --abbrev=0)
          new_tag=$((previous_tag + 1))
          echo "::set-output name=tag::$new_tag"

      - name: Create new release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag: ${{ steps.get_previous_tag.outputs.tag }}
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
