name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Позволяет запускать workflow вручную

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create ZIP archive
        run: |
          zip -r release.zip . -x README.md update.json .github/*

      - name: Get previous tag
        id: get_previous_tag
        run: |
          echo "Fetching tags..."
          tags=$(git for-each-ref --format='%(refname:short)' refs/tags)
          echo "Tags found: $tags"
          
          if [ -n "$tags" ]; then
            previous_tag=$(echo "$tags" | sort -n | tail -n 1)  # Получаем максимальный тег
            echo "Previous tag: $previous_tag"
            new_tag=$((previous_tag + 1))
          else
            new_tag=1
          fi
          
          echo "New tag: ${new_tag}"
          echo "new_tag=${new_tag}" >> $GITHUB_ENV

      - name: Create new release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.new_tag }}  # Используем переменную окружения
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
